# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 462110356376ce02225d471aab2719e43751534020f3c5735554095a053b4f3ca75da6d766fbf59adbc46200a4b3971341cc1813d418165ede550b73b5a584aa

test:
  secret_key_base: 0687f961e8061ecd2098402d95179d07491d0d3d828c90b726435d5fa180c714c64b97c908ab1cc5cc5ef72f437c0cb70868544b3026956bbf7143513b6b1384

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
